name: fake-news-gpu
channels:
  - anaconda
  - conda-forge
  - hcc
  - esri
  - default
dependencies:
  - smart_open
  - nltk
  - autopep8
  - scikit-learn
  - numpy
  - pandas
  - tqdm
  - gin-config
  - pip
  - tensorflow-gpu=2.2.0 # CUDA Version: 11.5
  - tensorflow-hub
  - tensorflow-addons
  - pip:
    - tensorflow-text