name: fake-news-gpu-pytorch
channels:
  - pytorch
  - anaconda
  - conda-forge
  - default
dependencies:
  - smart_open
  - nltk
  - autopep8
  - scikit-learn
  - numpy
  - pandas
  - tqdm
  - transformers
  - cudatoolkit=11.3
  - pytorch