name: fake-news-gpu
channels:
  - anaconda
  - conda-forge
  - hcc
  - esri
  - default
dependencies:
  - smart_open
  - nltk
  - autopep8
  - scikit-learn
  - numpy
  - pandas
  - tqdm
  - gin-config
  - pip
  - tensorflow-gpu=2.5.0
  - tensorflow-hub=2.5.0
  - tensorflow-addons=2.5.0
  - pip:
    - tensorflow-text